import { useState, useEffect } from 'react';
import { FiUser, FiMail, FiPhone, FiMapPin, FiBook, FiCalendar, FiAward, FiShield } from 'react-icons/fi';
import { useUser } from '../../context/UserContext';
import ChangePasswordForm from './ChangePasswordForm';

function ProfileSettings() {
  const { currentUser, updateUserProfile, loading: contextLoading } = useUser();
  const [form, setForm] = useState({
    name: '',
    email: '',
    phone: '',
    address: '',
    // Student specific fields
    semester: '',
    batchYear: '',
    department: '',
    section: '',
    // Teacher specific fields
    employeeId: '',
    designation: '',
    personalEmail: '',
    // Admin specific fields
    role: '',
    permissions: []
  });
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);

  const semesters = ['1', '2', '3', '4', '5', '6', '7', '8'];
  const currentYear = new Date().getFullYear();
  const batchYears = Array.from({ length: 8 }, (_, i) => String(currentYear - i));
  const departments = ['CSE', 'ECE', 'EE', 'ME', 'CE', 'EIE', 'Physics', 'Chemistry', 'Mathematics', 'Humanities'];
  const designations = ['Professor', 'Associate Professor', 'Assistant Professor', 'Lecturer'];
  const sections = ['A', 'B', 'C', 'D'];

  useEffect(() => {
    if (currentUser) {
      setForm({
        name: currentUser.name || '',
        email: currentUser.email || '',
        phone: currentUser.phone || '',
        address: currentUser.address || '',
         // scholarId is generated by server and is read-only in most flows
        semester: currentUser.semester || '',
        batchYear: currentUser.batchYear || '',
        department: currentUser.department || '',
        section: currentUser.section || '',
        employeeId: currentUser.employeeId || '',
        designation: currentUser.designation || '',
        personalEmail: currentUser.personalEmail || '',
        role: currentUser.role || '',
        permissions: currentUser.permissions || []
      });
    }
  }, [currentUser]);



  const validate = () => {
    if (!form.name.trim()) {
      return 'Name is required.';
    }
    if (!form.email.trim()) {
      return 'Email is required.';
    }
    if (form.email && !/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i.test(form.email)) {
      return 'Invalid email address.';
    }
    if (form.phone && !/^\d{10,15}$/.test(form.phone)) {
      return 'Phone should be 10-15 digits.';
    }
    if (!form.address.trim()) {
      return 'Address is required.';
    }

    // Role-specific validation
      if (currentUser?.role === 'student') {
      if (!form.semester) return 'Please select semester.';
      if (!form.batchYear) return 'Please select batch year.';
      if (!form.department) return 'Please select department.';
      if (!form.section) return 'Please select section.';
    }

    if (currentUser?.role === 'teacher') {
      if (!form.employeeId.trim()) return 'Employee ID is required.';
      if (!form.designation) return 'Please select designation.';
      if (!form.department) return 'Please select department.';
      if (form.personalEmail && !/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i.test(form.personalEmail)) {
        return 'Invalid personal email address.';
      }
    }

    return '';
  };

  const handleChange = e => {
    setForm({ ...form, [e.target.name]: e.target.value });
    setError('');
  };

  const handleSubmit = async e => {
    e.preventDefault();
    setError('');
    const errMsg = validate();
    if (errMsg) {
      setError(errMsg);
      return;
    }
    setSaving(true);

    try {
      // Simulate API call - replace with actual API
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      // Update context
      updateUserProfile(form);
      setSuccess(true);
      setTimeout(() => setSuccess(false), 3000);
    } catch (err) {
      setError('Failed to update profile: ' + (err.response?.data?.message || err.message));
    } finally {
      setSaving(false);
    }
  };

  const handleRoleChange = (newRole) => {
          // Role update functionality would be handled by admin
    setError('');
    setSuccess(false);
  };

  if (contextLoading) {
    return (
      <div className="max-w-4xl mx-auto mt-8">
        <div className="bg-white rounded-lg shadow p-6">
          <div className="animate-pulse">
            <div className="h-4 bg-gray-200 rounded w-1/4 mb-4"></div>
            <div className="space-y-3">
              <div className="h-10 bg-gray-200 rounded"></div>
              <div className="h-10 bg-gray-200 rounded"></div>
              <div className="h-10 bg-gray-200 rounded"></div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto">
      {/* Role Selector */}
      <div className="bg-white rounded-lg shadow p-6 mb-6">
        <h3 className="text-lg font-semibold mb-4 flex items-center">
          <FiShield className="mr-2" />
          User Role
        </h3>
        <div className="flex space-x-4">
          {['admin', 'teacher', 'student'].map((role) => (
            <button
              key={role}
              onClick={() => handleRoleChange(role)}
              className={`px-4 py-2 rounded-lg font-medium transition-colors ${
                currentUser?.role === role
                  ? 'bg-blue-600 text-white'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
              }`}
            >
              {role.charAt(0).toUpperCase() + role.slice(1)}
            </button>
          ))}
        </div>
      </div>

      {/* Profile Form */}
      <div className="bg-white rounded-lg shadow p-6">
        <h2 className="text-2xl font-bold mb-6 flex items-center">
          <FiUser className="mr-2" />
          Profile Settings - {currentUser?.role ? currentUser.role.charAt(0).toUpperCase() + currentUser.role.slice(1) : 'User'}
        </h2>
        
        {error && (
          <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded mb-4">
            {error}
          </div>
        )}
        
        {success && (
          <div className="bg-green-50 border border-green-200 text-green-700 px-4 py-3 rounded mb-4">
            Profile updated successfully!
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Basic Information */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label className="flex text-sm font-medium text-gray-700 mb-2 items-center">
                <FiUser className="mr-1" />
                Full Name *
              </label>
              <input
                name="name"
                value={form.name}
                onChange={handleChange}
                className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                required
              />
            </div>

            <div>
              <label className="flex text-sm font-medium text-gray-700 mb-2 items-center">
                <FiMail className="mr-1" />
                Email *
              </label>
              <input
                name="email"
                value={form.email}
                onChange={handleChange}
                className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                type="email"
                required
              />
            </div>

            <div>
              <label className="flex text-sm font-medium text-gray-700 mb-2 items-center">
                <FiPhone className="mr-1" />
                Phone Number
              </label>
              <input
                name="phone"
                value={form.phone}
                onChange={handleChange}
                className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                placeholder="Enter phone number"
                maxLength="15"
              />
            </div>

            <div>
              <label className="flex text-sm font-medium text-gray-700 mb-2 items-center">
                <FiMapPin className="mr-1" />
                Address *
              </label>
              <input
                name="address"
                value={form.address}
                onChange={handleChange}
                className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                required
              />
            </div>
          </div>

          {/* Student Specific Fields */}
          {currentUser?.role === 'student' && (
            <div className="border-t pt-6">
              <h3 className="text-lg font-semibold mb-4 flex items-center">
                <FiBook className="mr-2" />
                Student Information
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {/* Scholar ID removed from editable profile settings */}

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Department *</label>
                  <select
                    name="department"
                    value={form.department}
                    onChange={handleChange}
                    className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    required
                  >
                    <option value="">Select Department</option>
                    {departments.map(dept => (
                      <option key={dept} value={dept}>{dept}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Section *</label>
                  <select
                    name="section"
                    value={form.section}
                    onChange={handleChange}
                    className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    required
                  >
                    <option value="">Select Section</option>
                    {sections.map(sec => (
                      <option key={sec} value={sec}>{sec}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Semester *</label>
                  <select
                    name="semester"
                    value={form.semester}
                    onChange={handleChange}
                    className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    required
                  >
                    <option value="">Select Semester</option>
                    {semesters.map(sem => (
                      <option key={sem} value={sem}>{sem}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Batch Year *</label>
                  <select
                    name="batchYear"
                    value={form.batchYear}
                    onChange={handleChange}
                    className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    required
                  >
                    <option value="">Select Batch Year</option>
                    {batchYears.map(year => (
                      <option key={year} value={year}>{year}</option>
                    ))}
                  </select>
                </div>
              </div>
            </div>
          )}

          {/* Teacher Specific Fields */}
          {currentUser?.role === 'teacher' && (
            <div className="border-t pt-6">
              <h3 className="text-lg font-semibold mb-4 flex items-center">
                <FiAward className="mr-2" />
                Teacher Information
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Employee ID *</label>
                  <input
                    name="employeeId"
                    value={form.employeeId}
                    onChange={handleChange}
                    className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    required
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Designation *</label>
                  <select
                    name="designation"
                    value={form.designation}
                    onChange={handleChange}
                    className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    required
                  >
                    <option value="">Select Designation</option>
                    {designations.map(desig => (
                      <option key={desig} value={desig}>{desig}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Department *</label>
                  <select
                    name="department"
                    value={form.department}
                    onChange={handleChange}
                    className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    required
                  >
                    <option value="">Select Department</option>
                    {departments.map(dept => (
                      <option key={dept} value={dept}>{dept}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Personal Email</label>
                  <input
                    name="personalEmail"
                    value={form.personalEmail}
                    onChange={handleChange}
                    className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    type="email"
                    placeholder="personal@email.com"
                  />
                </div>
              </div>
            </div>
          )}

          {/* Admin Specific Fields */}
          {currentUser?.role === 'admin' && (
            <div className="border-t pt-6">
              <h3 className="text-lg font-semibold mb-4 flex items-center">
                <FiShield className="mr-2" />
                Admin Information
              </h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Role</label>
                  <input
                    name="role"
                    value={form.role}
                    onChange={handleChange}
                    className="w-full border border-gray-300 rounded-lg px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    placeholder="System Administrator"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">Permissions</label>
                  <div className="space-y-2">
                    {form.permissions.map((permission, index) => (
                      <div key={index} className="flex items-center">
                        <input
                          type="checkbox"
                          checked={true}
                          className="rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                          readOnly
                        />
                        <span className="ml-2 text-sm text-gray-700">{permission}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Submit Button */}
          <div className="border-t pt-6">
            <button
              type="submit"
              disabled={saving}
              className={`px-6 py-3 bg-gradient-to-r from-blue-600 to-indigo-700 text-white rounded-lg hover:opacity-90 transition shadow-md flex items-center ${
                saving ? 'opacity-60 cursor-not-allowed' : ''
              }`}
            >
              {saving ? (
                <>
                  <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                  Saving...
                </>
              ) : (
                <>
                  <FiUser className="mr-2" />
                  Save Changes
                </>
              )}
            </button>
          </div>
        </form>
      </div>

      {/* Change Password Section */}
      <ChangePasswordForm />
    </div>
  );
}

export default ProfileSettings;
